### PR TITLE
Fix loadStateField evaluator to address #1092

### LINKED ISSUE #1092: Nightly build failures
Couple builds broken this morning. It looks like it's due to recent PRs. @mperego do you want to take a look?

### PR DESCRIPTION
**Pull request by mperego**
Apparently linear access of Kokkos dynamic rank views is no longer working. 
Not sure if this is a bug (DynRankView is not as widely tested as View) or expected behavior.  
Fixes #1092

### CODE REVIEW

File: src/evaluators/state/PHAL_LoadStateField_Def.hpp [hunk 1]
```diff
@@ -51,15 +50,13 @@ void LoadStateFieldBase<EvalT, Traits, ScalarType>::evaluateFields(typename Trai
...
 
-  MDFieldVectorRight<ScalarType> g(data);
-  dataVec = g;
+  ALBANY_ASSERT (stateData.rank() <= 3, "Current implementation supports only views with rank up to 3. If larger rank is needed modify code below");
 
   Kokkos::parallel_for(this->getName(),
-                       Kokkos::RangePolicy<ExecutionSpace>(0,data.size()),
-                       KOKKOS_CLASS_LAMBDA(const int i) {
-    dataVec[i] = (i < stateToLoad_size) ? stateData(i) : 0.0;
+                       Kokkos::MDRangePolicy<ExecutionSpace, Kokkos::Rank<3>>({0,0,0},{stateData.extent(0),stateData.extent(1),stateData.extent(2)}),
```
Comment (bartgol) [inline src/evaluators/state/PHAL_LoadStateField_Def.hpp:57]: This works cause we use DynRankView, so usince 3 indices is always ok (we just have extent(1) and extent(2) that may be 1), right?

**Review by bartgol — APPROVED** [review]
Sneaky. That was a great find Mauro, thanks!

**Review by mcarlson801 — APPROVED** [review]
Nice catch! This change looks good to me.

**Comment by mperego** [comment]
Another alternative would be to deep_copy the state view into the MDfiled view, but this is a bit more fragile and it expects the views to have same properties (e.g. Kokkos layouts).

**Review by bartgol — APPROVED** [review]

**Comment by mcarlson801** [comment]
> An alternative would be to deep_copy the state view into the MDfiled view, but this is a bit more fragile and it expects the views to have same properties (e.g. Kokkos layouts).

I can confirm this doesn't work, I tried this awhile back before using an MDField iterator.

File: src/evaluators/state/PHAL_LoadStateField_Def.hpp (hunk 1 above)
Comment (jewatkins) [reply src/evaluators/state/PHAL_LoadStateField_Def.hpp:57]: kind of weird that this works for rank<3 but nice that it does since it seems a lot simpler.

**Review by jewatkins — CHANGES_REQUESTED** [review]
this seems to point to some issue with `MDFieldVectorRight`. could you finish removing it from the code? It looks like it's only in a few other places: ScatterScalarResponse, SeparableScatterScalarResponse, and PHAL_Utilities

**Comment by mcarlson801** [comment]
> this seems to point to some issue with `MDFieldVectorRight`. could you finish removing it from the code? It looks like it's only in a few other places: ScatterScalarResponse, SeparableScatterScalarResponse, and PHAL_Utilities

The DynRankView that is causing problems is the one in stateData, I'm pretty sure. MDFieldVectorRight is designed to be accessed linearly.

**Comment by mperego** [comment]
Yes, I agree, stateData was the issue.

**Review by jewatkins — APPROVED** [review]
ah okay, then it's fine.
